spring:
  profiles:
    active: dev
  application:
    name: Apboa
  servlet:
    multipart:
      max-file-size: 30MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
